# Generated by Django 3.0.3 on 2020-04-19 16:29

from django.db import migrations, models
import django.db.models.deletion
import django_fsm


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('state', django_fsm.FSMIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Done')], default=0)),
                ('linked_task', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Task')),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['title'], name='api_task_title_3cbbff_idx'),
        ),
    ]
